#! /usr/bin/env python

import sys
from darkflow.cli import cliHandler

# cliHandler(sys.argv)

argv = ['flow', 
'--model', 'cfg/yolov2-tiny.cfg', 
'--load' ,'weight/yolov2-tiny.weights',
'--labels', 'label/coco.names',
'--savepb']
# '--epoch', '10',
# '--lr', '1e-4',
# '--batch', '1',
# '--train', '--dataset', 'train_cdc/train_images', 
# '--annotation', 'train_cdc/train_annotations', 
# '--gpuName' , '/gpu:1',

cliHandler(argv)


